spring.application.name=Althaea

#API
spoonacular.api.key=9ceaa1b0334e4902ba1a4975fc1dc0b5

#Server
server.port=8080

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/althaea
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
althaea.jwt.secret=althaea-secret-key-change-this-in-production
althaea.jwt.expiration=86400000
